# Format: dart format .
# Lint: dart analyze

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'build/**'
    - '.dart_tool/**'
    - '.github/**'
    - '.vscode/**'
    - '.idea/**'
  language:
    strict-raw-types: true

linter:
  rules:
    avoid_print: false
    public_member_api_docs: false

    function_body_lines_limit: 50 
    class_member_lines_limit: 300
    file_lines_limit: 500       
    cyclomatic_complexity: 10    
    block_nesting_depth: 5      

formatter:
  line_length: 120 
  indent: ['space', 2] 