name: today_list
description: "Today List is a tab-based categorized, colorful to-do list designed for efficient task management throughout the day, featuring two types of iOS widgets."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI関連
  cupertino_icons: ^1.0.8
  flutter_progress_hud: ^2.0.2
  font_awesome_flutter: ^10.7.0
  flutter_slidable: ^4.0.0
  reorderables: ^0.6.0
  popover: ^0.3.1

  # ユーティリティ
  intl: ^0.19.0
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.2
  flutter_colorpicker: ^1.1.0

  # 外部のツール
  google_mobile_ads: ^5.1.0

  # アイコン・スプラッシュ画面
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1

  # 状態管理
  flutter_riverpod: ^2.4.9
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.9

  # データモデル・シリアライズ
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  app_links: ^6.4.0
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 静的解析・開発補助
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  freezed: ^2.4.5

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  # image_path: "assets/tl_sun.png"
  image_path: "assets/tl_lime.png"
  # image_path: "assets/tl_marine.png"
  # image_path: "assets/tl_cherry.png"
  # image_path: "assets/tl_pastry.png"
  # image_path: "assets/tl_note.png"
  remove_alpha_ios: true

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/native_splash.png

    - assets/tl_sun.png
    - assets/tl_lime.png
    - assets/tl_marine.png
    - assets/tl_cherry.png
    - assets/tl_pastry.png
    - assets/tl_note.png
