name: today_list
description: "Today List is a two-level categorized, colorful to-do list that helps you easily track and complete tasks for the day, with support for an iOS widget and an Apple Watch app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI関連
  cupertino_icons: ^1.0.8
  flutter_progress_hud: ^2.0.2
  font_awesome_flutter: ^10.7.0
  flutter_slidable: ^4.0.0
  reorderables: ^0.6.0
  popover: ^0.3.1

  # ユーティリティ
  intl: ^0.19.0
  uuid: ^4.5.1
  flutter_vibrate: ^1.3.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.2
  flutter_colorpicker: ^1.1.0

  # 外部のツール
  google_mobile_ads: ^5.1.0

  # アイコン・スプラッシュ画面
  flutter_native_splash: ^2.3.5
  flutter_dynamic_icon: ^2.1.0
  flutter_launcher_icons: ^0.13.1

  # 状態管理
  flutter_riverpod: ^2.4.9
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.9

  # データモデル・シリアライズ
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uni_links: ^0.5.1
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 静的解析・開発補助
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  freezed: ^2.4.5
  
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/tl_sun.png"
  # image_path: "assets/tl_lime.png"
  # image_path: "assets/tl_marine.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: '#ffffff'
  image: 'assets/native_splash.png'
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/native_splash.png

    - assets/tl_sun.png
    - assets/tl_lime.png
    - assets/tl_marine.png
    - assets/tl_cherry.png
    - assets/tl_pastry.png
    - assets/tl_notebook.png