name: Build for Production

on:
  workflow_call:
    inputs:
      release_tag:
        description: "Optional GitHub Release tag (e.g., v1.2.3)"
        required: false
        type: string
      pr_number:
        description: "Pull Request Number (if applicable, otherwise 0)"
        required: false
        type: number
        default: 0
    outputs:
      android_bundle_artifact_name:
        description: "Name of the Android App Bundle artifact"
        value: "ci-android-bundle"
      android_apks_artifact_name:
        description: "Name of the Android APKs artifact"
        value: "ci-android-apks"
      ios_apks_artifact_name:
        description: "Name of the Android APKs artifact"
        value: "ci-android-apks"
      ios_xcarchive_artifact_name:
        description: "Name of the iOS XCArchive artifact"
        value: "ci-ios-xcarchive"

jobs:
  build-android-release:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ job.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: true

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create dummy .env file
        run: touch .env

      - name: Install dependencies
        run: flutter pub get

      - name: Clean Gradle Cache and Build Output
        run: |
          rm -rf $HOME/.gradle/caches
          rm -rf $HOME/.gradle/daemon
          rm -rf $HOME/.gradle/wrapper
          ./android/gradlew --stop || true
          rm -rf android/.gradle
          rm -rf android/build
          rm -rf android/app/build

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Android App Bundle (Release)
        run: flutter build appbundle --release -Porg.gradle.java.home="$JAVA_HOME"

      - name: Build Android APKs (Release)
        run: flutter build apk --release --split-per-abi -Porg.gradle.java.home="$JAVA_HOME"

      - name: Upload Android App Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-android-bundle
          path: build/app/outputs/bundle/release/*.aab
          retention-days: 7

      - name: Upload Android APKs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-android-apks
          path: build/app/outputs/flutter-apk/*-release.apk
          retention-days: 7

  build-ios-release:
    runs-on: macos-latest
    outputs:
      result: ${{ job.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: true

      - name: Create dummy .env file
        run: touch .env

      - name: Install dependencies
        run: flutter pub get

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build iOS Archive (Release, No Code Signing)
        run: flutter build ios --release --no-codesign

      - name: Upload iOS Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-ios-xcarchive
          path: build/ios/archive/Runner.xcarchive
          retention-days: 7

  create-github-release:
    needs: [build-android-release, build-ios-release]
    runs-on: ubuntu-latest
    if: |
      inputs.release_tag != '' &&
      needs.build-android-release.outputs.result == 'success' &&
      needs.build-ios-release.outputs.result == 'success'
    permissions:
      contents: write
      actions: read
    steps:
      - name: Download Android Bundle Artifact
        uses: actions/download-artifact@v4
        with:
          name: ci-android-bundle
          path: ./release-assets/android

      - name: Download Android APKs Artifact
        uses: actions/download-artifact@v4
        with:
          name: ci-android-apks
          path: ./release-assets/android

      - name: Download iOS Archive Artifact
        uses: actions/download-artifact@v4
        with:
          name: ci-ios-xcarchive
          path: ./release-assets/ios

      - name: List downloaded artifacts
        run: ls -lR ./release-assets

      - name: Create GitHub Release Draft
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.release_tag }}
          name: Release ${{ inputs.release_tag }}
          draft: true
          prerelease: false
          files: |
            ./release-assets/android/*.aab
            ./release-assets/android/*.apk
            ./release-assets/ios/Runner.xcarchive
