name: Today List CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  format-and-analyze:
    name: Code Quality Check
    uses: ./.github/workflows/code-quality.yml
    permissions:
      contents: read

  test:
    name: Flutter Test
    uses: ./.github/workflows/flutter-test.yml
    permissions:
      contents: read

  report:
    name: Test Report
    needs: test
    if: always() && github.event_name == 'pull_request' 
    uses: ./.github/workflows/test-reporter.yml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
    permissions:
      checks: write
      actions: read
      pull-requests: write
    secrets: inherit

  review:
    name: Copilot Review
    needs: test
    if: github.event_name == 'pull_request' && needs.test.result == 'success'
    uses: ./.github/workflows/copilot-review.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
    permissions:
      pull-requests: write
      contents: read
    secrets: inherit

  release-build:
    name: Build App (Android & iOS)
    needs: [format-and-analyze, test]
    if: |
      needs.format-and-analyze.result == 'success' &&
      needs.test.result == 'success'
    uses: ./.github/workflows/build-for-production.yml
    with:
      release_tag: '' 
    permissions:
      contents: write
      actions: read
    secrets: inherit

  notify:
    name: Notify Completion
    needs: [format-and-analyze, test, report, review, release-build]
    if: always() && github.event_name == 'pull_request'
    uses: ./.github/workflows/notify-completion.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      run_id: ${{ github.run_id }}
      code_quality_needs: ${{ toJSON(needs.format-and-analyze) }}
      flutter_test_needs: ${{ toJSON(needs.test) }}
      test_report_needs: ${{ toJSON(needs.report) }}
      code_review_needs: ${{ toJSON(needs.review) }}
      production_build_needs: ${{ toJSON(needs.release-build) }}
    permissions:
      pull-requests: write
      actions: read
    secrets: inherit