name: Code Quality Check

on:
  workflow_call:
    outputs:
      result:
        description: "Check Result (success/failure)"
        value: ${{ jobs.check.outputs.result }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: true

      - name: Create dummy .env file
        run: touch .env

      - name: Install dependencies
        run: flutter pub get

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run Dart Format Check
        id: format
        run: dart format --set-exit-if-changed .

      - name: Run Dart Analyze
        id: analyze
        run: dart analyze

      - name: Set result status
        id: set-result
        if: always()
        run: |
          if [[ "${{ steps.format.outcome }}" == "success" && \
                "${{ steps.analyze.outcome }}" == "success" ]]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "Code quality checks passed."
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "Code quality checks failed."
            if [[ "${{ steps.format.outcome }}" != "success" ]]; then
              echo "::error::Code formatting issues found. Run 'dart format .' locally and commit changes."
            fi
            if [[ "${{ steps.analyze.outcome }}" != "success" ]]; then
              echo "::error::Dart analysis found issues."
            fi
            exit 1
          fi 